### ISSUE TITLE
Some weird Directory Error

### ISSUE THREAD

**Issue by flixi67** [MisterXY89/iliasScraper#1]
>>> sc.run()
                 ILIAS SCRAPER
 - american_welfare -

>> Getting all folder urls...
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100096.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100104.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100109.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100116.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100124.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100131.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100145.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100153.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100157.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100162.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100166.html
https://ilias.uni-konstanz.de/ilias/goto_ilias_uni_fold_1100170.html

>> Starting download
War_on_Poverty_to_War_on_Welfare_(American_Welfare_State)/Week_5:_Labor_Markets
Altonji, Employment Effects of UI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Felix\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\iliasScraper\scraper.py", line 33, in run
    self.controller.download(self.url, name=self.name)
  File "C:\Users\Felix\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\iliasScraper\controller.py", line 56, in download
    self.download_handler.download(file, path, self.ignore_endings)
  File "C:\Users\Felix\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\iliasScraper\download_handler.py", line 47, in download
    self._verify_path(path)
  File "C:\Users\Felix\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\iliasScraper\download_handler.py", line 67, in _verify_path
    os.makedirs(sub_path, mode=0o777), #mode = 0o666)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] Der Verzeichnisname ist ungültig: '/Users/Felix/OneDrive - bwedu/Documents/Studium/WiSe2021/American Welfare scrape/War_on_Poverty_to_War_on_Welfare_(American_Welfare_State)/Week_5:_Labor_Markets'
>>>

**Comment by MisterXY89** [comment]
version 0.1.5 had a few bugs, should be resolved with [v0.1.6](https://github.com/MisterXY89/iliasScraper/releases/tag/v0.1.6).
Try `pip install iliasScraper --upgrade` and try again

**Comment by flixi67** [comment]
`>>> sc.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Felix\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\iliasScraper\scraper.py", line 32, in run
    self.controller.init_controller()
AttributeError: 'Scraper' object has no attribute 'controller'`

**Comment by MisterXY89** [comment]
should be resolved with version v0.1.7, if not, just reopen the issue
